### ISSUE TITLE
PAs have managers and an 'is_manager' flag - but no validation that manager also is_manager

### ISSUE THREAD

**Issue by kws** [SocialFinanceDigitalLabs/lw-ng#8]
PAs have managers and an 'is_manager' flag - but no validation that manager also is_manager

A slightly more helpful model may be to have an additional Manager model so that the the PA.manager relationship is to a Manager profile - that way we can ensure referential integrity.

**Comment by kws** [comment]
@cyramic - any idea if there may be managers who are not themselves PAs? 

It's a question of whether the inheritance should be User <- PersonalAdvisor <- PAManager

(although I'm not sure there is much benefit to that, and it would be more flexible if User <- PAManager) ?

**Comment by cyramic** [comment]
In 9 cases out of 10, it does indeed go YP -> PA -> Manager. In reality, however, it got a lot more complex than that once LAs started using Leaving Well.

Where it got complex is that Managers can have young people assigned to them as well as PAs. That's why we tried to simplify it down so that a manager was merely a PA type which made the rest of the structure easier to implement. If we were to separate PAs and Managers, then we'd to think about how to represent the complex relationship between the three types.

Not only that, but a YP may even be given multiple PAs (if a PA is in training, maternity leave, part time, etc). It almost looks like this in the worst case scenario...

```mermaid
erDiagram
PA }|--o{ YP: "assigned to"
Manager }|--o{ PA: "assigned to"
Manager }|--o{ YP: "assigned to"
```

Saying all that, it becomes a matter of what would be useful for the project now that we're open sourcing it.  Does the relationship I described above make this too complex?  If so, we could just restrict things to make it simpler...

**Comment by kws** [comment]
It's interesting that you think of it as more complex. 

It's exactly to avoid the situation above I was thinking more along the lines of them being separate "facets". 

There are users, and users can have the "YP" facet, the "PA" facet, or the "Manager" facet.

They are independent, i.e. you can have a user that's a manager without being a PA, a PA without being manager, or they could be both. 

In theory this would also allow users to have PA and YP facet at the same time, although I expect that would rarely happen in a real scenario.

**Comment by cyramic** [comment]
Based on our discussion, we're looking for a relationship something like this.  The Manager-YP link would be handled by the fact that a user could be linked to a manager AND a PA, and PAs have that link already.

```mermaid
erDiagram
User ||--|| PA: "is a"
User ||--|| Manager: "is a"
User |o--|| YP: "can be represented by"
PA }|--|{ YP: "assigned to"
Manager }|--|| PA: "assigned to"
```
